server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: synthetics-instruction-service
  
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: BASIC
  
  # Eureka client configuration
  cloud:
    discovery:
      enabled: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Logging configuration
logging:
  level:
    com.finos.synthetics.instruction: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom application properties
app:
  instruction:
    timeout:
      default: 30
      max: 300
    validation:
      enabled: true
    handler:
      service:
        name: synthetics-handler-service
        url: http://localhost:8082 